### ISSUE TITLE
Parsing classes with imports 

### ISSUE THREAD

**Issue by d9k** [sinclairzx81/typebox-codegen#33]
Seems `typebox-codegen` which is used by [ts2typebox](https://github.com/xddq/ts2typebox) can't parse `class` and doesn't process imports

```ts
import { Column, DataType, Default, Model, Table } from 'sequelize-typescript';

@Table
export class CarBrand extends Model<CarBrand> {
  @Column
  name: string;

  @Default(true)
  @Column(DataType.BOOLEAN)
  isCertified: boolean;

  @Column
  imgUrl: string;

  @Column
  orderNo: number;

  @Column
  carsCount: number;
}
```

(example from [sequelize-typescript-migration-lts/README](https://github.com/mmRoshani/sequelize-typescript-migration/blob/master/README.md#usage-example))

```
> ts2typebox -i carBrand.ts --output-stdout
Unhandled: ImportDeclaration import { Column, DataType, Default, Model, Table } from 'sequelize-typescript';
/**
 * ATTENTION. This code was AUTO GENERATED by ts2typebox. While I don't know
 * your use case, there is a high chance that direct changes to this file get
 * lost. Consider making changes to the underlying Typescript code you use to
 * generate this file instead. The default file is called "types.ts", perhaps
 * have a look there! :]
 */
```

It would be very nice to be able to create skeleton of TypeBox validators from database models code.

I opened [an issue at ts2typebox](https://github.com/xddq/ts2typebox/issues/25) and maintainer [answered](https://github.com/xddq/ts2typebox/issues/25#issuecomment-1981496735):

> @xddq:
>
> this package is nowadays just a simple wrapper around [typebox-codegen](https://github.com/sinclairzx81/typebox-codegen) . I think you should mention the issue there. Once it is fixed updating the dependencies here is no problem.

**Comment by sinclairzx81** [comment]
@d9k Hi,

The code generators for this project will only generate from TS types (which would otherwise be erased by the compiler), but avoids runtime constructs like classes, functions and variables, so not sure there's much that can be done here on that front. Also, it wouldn't be possible to generate from library specific decorators as these carry no type information and are only really meaningful to a specific library (`sequelize-typescript` in this case).

Note that this project intentionally limits itself to TS programmable types only (so `interface` and `type` definitions). Anything above this is currently considered "out of scope". But in the case of the `CarBrand` class, did you have any thoughts on what should this generate?

Open to thoughts!
S

**Comment by sinclairzx81** [comment]
@d9k Heya, 

Going to close this one off as deriving type definitions from class definition is currently out of scope due to classes having a runtime aspect to them. A possibility may exist to derive a classes public interface as a Type.Constructor() in future tho, but for now, I'm going to limit code generation to only erasable types (limiting to only `type` and `interface` definitions)

Cheers
S
