### ISSUE TITLE
Refinement for template literals is lost on transform

### ISSUE THREAD

**Issue by kade-robertson** [sinclairzx81/typebox-codegen#35]
Take the following input types ([workbench](https://sinclairzx81.github.io/typebox-workbench/?share=Ly8gRWRpdCBUeXBlU2NyaXB0IFR5cGVzIEhlcmUuIFVzZSBDdHJsICsgUyB0byBTaGFyZQoKLyoqCiAqIEBtaW5MZW5ndGggMTYKICogQG1heExlbmd0aCAxNgogKiBAcGF0dGVybiAiW2EtejAtOV17MTZ9IgogKi8KZXhwb3J0IHR5cGUgQmFzZSA9IHN0cmluZzsKCmV4cG9ydCB0eXBlIFdpdGhQcmVmaXggPSBgcHJlZml4LSR7QmFzZX1gOw%3D%3D)):
```ts
/**
 * @minLength 16
 * @maxLength 16
 * @pattern "[a-z0-9]{16}"
 */
export type Base = string;

export type WithPrefix = `prefix-${Base}`;
```

The generated TypeBox definitions appear to be correct:
```ts
import { Type, Static } from '@sinclair/typebox'

export type Base = Static<typeof Base>
export const Base = Type.String({
  minLength: 16,
  maxLength: 16,
  pattern: '[a-z0-9]{16}'
})

export type WithPrefix = Static<typeof WithPrefix>
export const WithPrefix = Type.TemplateLiteral([Type.Literal('prefix-'), Base])
```

There are a few issues:

1. The refinement steps for the `Base` string are lost in definitions of `WithPrefix` in other exports. In `io-ts`, for example:
```ts
import t from 'io-ts'

export type Base = t.TypeOf<typeof Base>
export const Base = t.refinement(
  t.string,
  (value) => value.length >= 16 && value.length <= 16
)

export type WithPrefix = t.TypeOf<typeof WithPrefix>
export const WithPrefix = t.refinement(t.string, (value) =>
  /^prefix-(.*)$/.test(value)
)
```
This might be a bit of a harder one to fix, but can maybe be done by evaluating the contents of each match group with the refinement of their respective types? (Maybe not in all export options)

2. All non-TypeBox types appear to lose the pattern on `Base` entirely:
```ts
import * as v from 'valibot'

export type Base = v.Output<typeof Base>
export const Base = v.string([v.maxLength(16), v.minLength(16)])

export type WithPrefix = v.Output<typeof WithPrefix>
export const WithPrefix = v.string([v.regex(/^prefix-(.*)$/)])
```

3. The re-generated TypeScript types convert the template literal type to `unknown`:
```ts
export type Base = string
export const Base = (() => {
  const local_0 = /[a-z0-9]{16}/
  function check_Base(value: any): boolean {
    return (
      typeof value === 'string' &&
      value.length <= 16 &&
      value.length >= 16 &&
      local_0.test(value)
    )
  }
  return function check(value: any): value is Base {
    return check_Base(value)
  }
})()

export type WithPrefix = unknown
export const WithPrefix = (() => {
  const local_0 = /^prefix-(.*)$/
  function check_WithPrefix(value: any): boolean {
    return typeof value === 'string' && local_0.test(value)
  }
  return function check(value: any): value is WithPrefix {
    return check_WithPrefix(value)
  }
})()
```

**Comment by sinclairzx81** [comment]
@kade-robertson Hi,

Unfortunately, this is probably a no-fix. In TypeBox, when combining a String with a TemplateLiteral. TypeBox will discard any constraints applied to that String (i.e. `pattern`, `minLength` and `maxLength`). The reason for this is that TypeBox needs to be able to parse and generate types from Regular Expressions, and additional syntax embeddings (such as the `{16}` in `[a-z0-9]{16}`) are deemed out of scope because they are not supported in TypeScript template literal types (at least as of today).

In a nutshell, because TypeBox's implementation of TemplateLiterals is built on top of a very narrow subset of Regular Expressions, there is no way to encode the string constraints within the Regular Expression in a way that can be later parsed for generative types or reconciled back to a TS static type (as regular expressions cannot be typed in TS)

As a workaround, you can just do the following (if working through codegen)

```typescript
/**
 * @minLength 16
 * @maxLength 16
 * @pattern "[a-z0-9]{16}"
 */
export type Base = string;

/**
 * Tip: You don't need the minLength or maxLength constraints here
 * as they are handled by the expression.
 * 
 * @pattern "^prefix-[a-z0-9]{16}$"
 */
export type WithPrefix = string;
```
Unfortunately, this means that the `WithPrefix` won't have the `prefix-` constrained TS type. However, if you are using TypeBox directly, you can just write the following.

```typescript
export type WithPrefix = Static<typeof WithPrefix> // `prefix-${string}`
export const WithPrefix = Type.Unsafe<`prefix-${string}`>(Type.String({
  pattern: '^prefix-[a-z0-9]{16}$'
}))
```
This uses Unsafe to give the correct static type (but is unsafe as TS cannot safely guard against the length here). Due to the disparities between Regex and Template Literals, it's very unlikely the codegen project can do much here.

Hope this brings a bit of insight into this aspect. Will close off this issue for now as it is generally a no-fix (at least for now), but happy to discuss further on this thread if you have any follow up questions. 

Cheers!
S
