### ISSUE TITLE
Option to emit types wrapped in arrow function?

### ISSUE THREAD

**Issue by aleclarson** [sinclairzx81/typebox-codegen#52]
I'm using the TypeScript-to-TypeBox generator. I'd prefer to have all types in my TypeBox definitions be function calls, even my own types.

### Current output

```ts
export type StatusType = Static<typeof StatusType>
export const StatusType = Type.Union([
Type.Literal("pending"),
Type.Literal("active"),
Type.Literal("inactive"),
Type.Literal("archived")
])
```

### Desired output

```ts
export type StatusType = Static<ReturnType<typeof StatusType>>
export const StatusType = (options?: SchemaOptions) => Type.Union([
Type.Literal("pending"),
Type.Literal("active"),
Type.Literal("inactive"),
Type.Literal("archived")
], options)
```

**Comment by sinclairzx81** [comment]
@aleclarson Hi!

> I'd prefer to have all types in my TypeBox definitions be function calls, even my own types.

Ah, unfortunately, this may not be feasible under the current setup as wrapping types in functions is specifically reserved for generic type representation only.  For example consider [WorkBench Link Here](https://sinclairzx81.github.io/typebox-workbench/?share=ZXhwb3J0IHR5cGUgVmVjdG9yPFQ%2BID0gewogIHg6IFQsCiAgeTogVCwKICB6OiBUCn0%3D)

```typescript
// input
export type Vector<T> = {
  x: T,
  y: T,
  z: T
}

// output - Vector is treated as a template
export type Vector<T extends TSchema> = Static<ReturnType<typeof Vector<T>>>
export const Vector = <T extends TSchema>(T: T) =>
  Type.Object({
    x: T,
    y: T,
    z: T
  })
```
Using the Workbench link above, If you click on Zod for the Vector type above, take note that no code is generated. This is because generic types (wrapped in functions) act as templates for generic types, and the generators are setup to understand that functions mean generic templates. Note that if you use the type (i.e. create a Vertex type), this will result in code generation for Zod where the template is expanded into the location where it's embedded.

```typescript
export type Vector<T> = {
  x: T,
  y: T,
  z: T
}

export type Vertex = {
  position: Vector<number>,
  normal: Vector<number>,
  texcoord: Vector<number>,
}
```
will produce the following Zod output
```typescript
import { z } from 'zod'

export type Vertex = z.infer<typeof Vertex>
export const Vertex = z.object({
  position: z.object({
    x: z.number(),
    y: z.number(),
    z: z.number()
  }),
  normal: z.object({
    x: z.number(),
    y: z.number(),
    z: z.number()
  }),
  texcoord: z.object({
    x: z.number(),
    y: z.number(),
    z: z.number()
  })
})
```
So the thing that makes this difficult mostly stems from the mechanics around generic type representation and how the code generation is setup around it  ... this contrasted with making non-generic types into functions, which requires tracking whether or not a type is legitimately generic, or a wrapped type. 

Will close off this issue for now as I don't think there is much that can be done under the current system, but will make a note to explore this in more depth in later revisions. 

All the best!
S
